version: '3.7'

services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    ports:
      - "8182:8182"   # Gremlin Server port
    environment:
      - JANUS_PROPS_FILE=conf/janusgraph-inmemory.properties
    volumes:
      - janus-data:/var/lib/janusgraph

